name: golden_test_exemple
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  freezed:  
  freezed_annotation:
  dartz: ^0.10.1
  dio: ^4.0.6
  faker: ^2.0.0
  flutter_svg: ^1.0.3
  golden_toolkit: ^0.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  mockito:

flutter:
  uses-material-design: true
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/gotham-book.otf
          weight: 400
        - asset: assets/fonts/gotham-bold.otf
          weight: 700
    - family: FSAlbert
      fonts:
        - asset: assets/fonts/FSAlbert.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularXXTT-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularXXTT-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/CircularXXTT-Regular.ttf
          weight: 400
        - asset: assets/fonts/CircularXXTT-Light.ttf
          weight: 200
        - asset: assets/fonts/CircularXXTT-LightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/CircularXXTT-Medium.ttf
          weight: 600
  assets:
   - assets/icon/